### ISSUE TITLE
Fix Google Analytics tracking code for http://investigativecenters.org

### ISSUE THREAD

**Issue by StephenAbbott** [ANCIR/InvestigativeCenters.org#4]
The Google Analytics tracking code being used on http://investigativecenters.org doesn't look to be recording any analytics in the dashboard I can see in the ANCIR GA account.

Please check and fix the tracking code.

**Comment by StephenAbbott** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1506468/12110212/6b65ec92-b392-11e5-820d-51c920cb0c1f.gif)

**Comment by DavidLemayian** [comment]
@StephenAbbott :joy:
